### ISSUE TITLE
@parameterized_class makes unnecessary assumption that snake_case is used for test methods names

### ISSUE THREAD

**Issue by przem14** [wolever/parameterized#101]
In one of projects I work on we're using camelCase. I wanted to decorate one of our TestCases using `@parameterized_class` decorator, and I encountered an issue where all tests did run for base instance (and obviously failed with errors). In decorator implementation there is `if method_name.startswith("test_"):` statement which imo could be more general. Afaik unittest, pytest and nose does not make assumptions regarding name convention, so I guess in this case underscore could be dropped also.

**Comment by bobwalker99** [comment]
oops sorry - only noticed this after my PR, see https://github.com/wolever/parameterized/pull/106

**Comment by wolever** [comment]
This will be included in the release coming out later today!
