### ISSUE TITLE
Is it possible to write unittests for async functions using @parameterized.expand?

### ISSUE THREAD

**Issue by SadiaAfrinPurba** [wolever/parameterized#137]
Hi, 

I want to test the async functions using the @parameterized.expand decorator. There is no error while executing the tests, but it shows zero test coverage. 

I'm using the @async_test decorator to test the async functions and without @parameterized.expand they work fine, meaning that it shows 100% code coverage.

```
from aioitertools.tests.helpers import async_test

class TestService(TestCase):
    def setUp(self) -> None:
        self.mock_query_details = {"column_id": 0}

    @parameterized.expand([
        ({"col1": ["", "a", "b", "c", "d", "", "", ""], "cluster": [0, 1, 1, 1, 1, 0, 0, 0]},
         [['a'], ['b'], ['c'], ['d']]),
        ({"col1": [" ", "a", "b", "c", "d", " ", " ", " "], "cluster": [0, 1, 1, 1, 1, 0, 0, 0]},
         [['a'], ['b'], ['c'], ['d']]),
    ])
    @async_test
    async def test_function(self, mock_data, expected):
        data_frame = pd.DataFrame(mock_data)
        num_rows = 4

        service = Service()
        actual = await service.function(query_detail=self.mock_query_details, data_frame=data_frame,
                                                       num_rows=num_rows)

        self.assertCountEqual(actual, expected)



```

Do I need to follow any extra steps for using the @parameterized.expand decorator to test the async function?

**Comment by dbungert** [comment]
Depending on python version this may work when paried with unittest.IsolatedAsyncioTestCase, or you may run into https://github.com/python/cpython/issues/101486

I started some fixes for this - https://github.com/wolever/parameterized/compare/master...dbungert:parameterized:expand-async - but am unsure about handling of pre-python 3.5.

**Comment by wolever** [comment]
This has been added in 0.9.0 thanks to , which will be on pypi in a day or so (https://github.com/wolever/parameterized/pull/135; thanks  @Ronserruya!)

**Comment by wolever** [comment]
It's up! https://pypi.org/project/parameterized/0.9.0/

**Comment by gaby** [comment]
@wolever Thanks!
