### ISSUE TITLE
Lazy creation parameterized_class attributes

### ISSUE THREAD

**Issue by anudeepsamaiya** [wolever/parameterized#139]
Is it possible to provide the attributes to `parametrize_class` decorators lazily, such that the test factory should run only when the particular test class is being executed?

```python
@parameterized_class(
    [{"address_object": x} for x in AddressFactory.create_batch(20)]
)
class SomeTests:
     pass
```

The `@parametrize` decorator supports taking a `function` as an argument, but `@parametrized_class` decorator does not support `functions` or `generators`.

**Comment by wolever** [comment]
It would be possible (PR very welcome!) to update `parameterized_class` to accept a callable, but unfortunately I'm not sure whether it would be possible to lazily evaluate that callable when the class under test is executed. Specifically, test runners typically collect all the tests to be run first, then execute them, and I'm not sure how this lazy evaluation would interact with that semantic.
