### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by ulgens** [wolever/parameterized#142]
After seeing the repo hasn't gotten any commits in the last 1.5 years, I wanted to check if it's still maintained and is there any plan for Python 3.10 support.

**Comment by avalanchy** [comment]
@wolever Would you be able to update tox.ini etc. for Python 3.10? Or if I will do it, will you review it and merge it?

**Comment by wolever** [comment]
Yep! Please do!

**Comment by wolever** [comment]
Done! Thanks y'all for the poke :)

**Comment by gaby** [comment]
@wolever Any plans to release v0.9.0 thanks

**Comment by wolever** [comment]
Hey! Yes! Work's been busy this week, but I'll be getting it out this weekend :)

**Comment by gaby** [comment]
Thanks! Looking forward!
