### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by adamchainz** [wolever/parameterized#32]
I love `nose-parameterized`, it's the best test parameterizer out there that I've seen.

We use `pytest` for our tests and I've had several conversations about how we use `nose-parameterized` and my colleague has said "but wait we use pytest" and I've had to re-explain that it's for all test runners.

A name change for the next version would solve all these conflicts. Name changes happen occasionally in the python community, e.g. recently `pep8` became `pycodestyle` to avoid confusion. Thoughts?

**Comment by jayvdb** [comment]
The name change for pycodestyle has had complications. I recommend waiting a bit longer for the dust to have settled, and then reading the various fallout re pycodestyle in order to avoid any avoidable problems. E.g. ongoing discussions on debian-python , etc.

**Comment by adamchainz** [comment]
I just gave it as an example, I doubt many of those complications will hold for `nose-parameterized` since it's not a standalone binary and would just require users' imports to change.

**Comment by wolever** [comment]
Thanks for the suggestions! Yea, I've definitely considered a name change, and I feel like it's stable enough now to warrant it.

I'll also poke a couple of the pycodestyle people to see what their experiences have been like. @jayvdb: if you know any of them and wouldn't mind pointing them at this thread to dump their $0.02 that would be really helpful!

Also: what names would y'all suggest? Maybe just a straight `parameterized`? I've grabbed the PyPI name just in case…

**Comment by adamchainz** [comment]
`test(s)?-parameterized` maybe?

**Comment by wolever** [comment]
Also, my transition plan (comments or suggestions here would be helpful):

[] Decide on a new name (at the moment I'm leaning towards `parameterized`, but not married to it)
[] Release the new package to PyPI and create GH repo.
[] Add `nose_parameterized` extras flag to new package so `pip install parameterized[nose_parameterized]` will install a dummy package named `nose_parameterized` which is just an alias for the new package (ie, so users can update without making any code changes beyond their `requirements.txt`)
[] Release a new version of `nose_parameterized` which includes a deprecation warning
[] Search around the internet and update, ex, StackOverflow answers

**Comment by adamchainz** [comment]
No need for a new repo, you can rename this GH repo and it will gain a redirect from GH: https://github.com/blog/1508-repository-redirects-are-here . You can also push the final version of `nose-parameterized` to PyPI with the URL updated to `github.com/wolever/whatever-it-is` too and that should deal with most repo references.

The dummy package sounds like a good idea but maybe overengineering?

**Comment by wolever** [comment]
> The dummy package sounds like a good idea but maybe overengineering?

Oh probably… but I like to live life on the edge 😜

**Comment by wolever** [comment]
Okay! I've finally made the switch! Would you mind poking around and double checking that everything installs correctly and such?

Also, although I love the idea of the dummy `nose_paramererized` package, I don't know how to do that :( Do you know how? Would you mind submitting a PR?

**Comment by adamchainz** [comment]
Dummy package could just be a single python file that does `from parametrized import *`, whilst maybe also outputting a warning. I'd do it as a separate mini package in a folder like you have in `misspelling-helper/nose-parametrized`.

**Comment by wolever** [comment]
Closing this issue, as the name change seems to be done 🙂
