### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Skeen** [wolever/parameterized#45]
Hello,

According to the METADATA information on the package;

    cat site-packages/nose_parameterized-0.5.0.dist-info/METADATA

    Metadata-Version: 2.0
    Name: nose-parameterized
    Version: 0.5.0
    License: UNKNOWN

Rather then UNKNOWN, perhaps it should say `Simplified BSD`.

Also the BSD License provided is a little messy with the 'tl;dr;' statement, which causes Github not to pick it up.

**Comment by wolever** [comment]
This should be fixed now 🙂
