### ISSUE TITLE
Maintain GitHub tags

### ISSUE THREAD

**Issue by Skeen** [wolever/parameterized#46]
Hello,

It appears that the GitHub tags for releases stopped Nov 6, 2014, while releases on the pip package manager continued.

PyPi announches the latest release as 0.6.1 of 2017-03-21, where's GitHub's most recent release is 0.3.5 of 2014-11-06.

Is there a specific reason why GitHub releases has been dropped from the release cycle? - Is it too much work to include again?

**Comment by wolever** [comment]
Hey! Thanks for the work y'all do 🙂 I've got the most recent release - 0.7.3 - tagged, and I'll keep the GH tags up to date from now on.
