### ISSUE TITLE
how to use param iterator？

### ISSUE THREAD

**Issue by tt33025515** [wolever/parameterized#54]

**Comment by tt33025515** [comment]
hello，can you show me how to use param iterator more specific？thank you very much！

**Comment by asutkarpeeyush** [comment]
@tt33025515 https://github.com/wolever/parameterized/blob/35eac710a5413ee18f18b3cb3cd7d4f7bd71327f/README.rst

**Comment by wolever** [comment]
Thanks @asutkarpeeyush! And if you have more questions, @tt33025515, please post them to StackOverflow - you'll get the best answers there :)
