### ISSUE TITLE
TypeError: type object argument after * must be a sequence, not float

### ISSUE THREAD

**Issue by asutkarpeeyush** [wolever/parameterized#55]
@wolever 
**When did I get this error?**
- While using something like this - 
```python
@parameterized.expand([123.0])
    def test_xyz(self, id: float) -> None:
```
**What is the cause?**
- args of float type aren't changed to tuple in this function
```python 
 @classmethod
    def from_decorator(cls, args):
        """ Returns an instance of ``param()`` for ``@parameterized`` argument
            ``args``::

                >>> param.from_decorator((42, ))
                param(args=(42, ), kwargs={})
                >>> param.from_decorator("foo")
                param(args=("foo", ), kwargs={})
            """
        if isinstance(args, param):
            return args
        if isinstance(args, string_types):
            args = (args, )
        return cls(*args)
```
**What is the work around I used?**
- passed a tuple
```python
@parameterized.expand([(123.0,)])
    def test_xyz(self, id: float) -> None:
```
**What could be the possible permananent fix?**
- It would be too soon for me to comment on this but is there a reason floats aren't converted to tuple in ```from_decorator()```?

**Comment by asutkarpeeyush** [comment]
@wolever Could you have a look at this?

**Comment by wolever** [comment]
Hey! Thanks for the ping. Yep, this is a good catch - we're doing it for strings, should probably also do it for numbers. If you want to throw together a PR that adds a check for numeric types, I'd definitely be up for reviewing + merging.

**Comment by asutkarpeeyush** [comment]
Would be happy to :)

**Comment by wolever** [comment]
Closing to clean up, will review any PR 🙂

**Comment by drudiger** [comment]
I guess this was never fixed? Just ran into it. Your documentation says:

> If a test function only accepts one parameter and the value is not iterable, then it is possible to supply a list of values without wrapping each one in a tuple
@parameterized([1, 2, 3])

However, if I try that, I get an error about an int not being iterable. I have to do @parameterized([(0,), (1,), (3,), (4,)]) to get it to work.
