### ISSUE TITLE
Setting skip_on_empty=True isn't workingon Python3

### ISSUE THREAD

**Issue by gaf3** [wolever/parameterized#57]
I have an empty list returned in some cases (only checks files that have changed). When I used the skip_on_empty settings, I got this output:

```
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

I change line 479 in parameterized.py from

```python
return wraps(f)(lambda: skip_on_empty_helper())
```
to
```python
return wraps(f)(skip_on_empty_helper)
```

And got the output I wanted

```
test_namespaced (test_namespace.TestNamespace) ... skipped 'parameterized input is empty'
```

**Comment by wolever** [comment]
Fixed! Will be pushing out in 0.7.4 shortly.
