### ISSUE TITLE
Version 0.6.2 not in PyPI ?

### ISSUE THREAD

**Issue by roni-frantchi** [wolever/parameterized#58]
Looking at https://github.com/wolever/parameterized/blob/master/CHANGELOG.txt#L1
You'd think 0.6.2 was released in 2018-03-11.

But looking at https://pypi.org/project/parameterized/#history or running `pip search` lists 0.6.1 as the latest, and there's no way to get 0.6.2 ...

```
$ pip search parameterized --index https://pypi.python.org/pypi
...

parameterized (0.6.1)                                           - Parameterized testing with any Python test
                                                                  framework
  INSTALLED: 0.6.1 (latest)

...
```

**Comment by wolever** [comment]
Huh strange. I've just push'd a new 0.7.0, though - do you still need 0.6.2 specifically?
