### ISSUE TITLE
Fixture are not meant to be called directly

### ISSUE THREAD

**Issue by Overdrivr** [wolever/parameterized#60]
With pytest 4.1.0, it is no longer possible to pass a fixture to a parameterized test:

```
import pytest
from parameterized import parameterized

@pytest.fixture
def gen_test():
    return [('foo',), ('bar',)]

@parameterized(gen_test)
def test_(arg):
    print(arg)
```

```
Fixture "gen_test" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```

Is there any workaround ? Ideally I would like to avoid passing a regular function (unless for some reason it's bad behavior) because my fixture is dependent on another fixture

**Comment by wolever** [comment]
Thanks for the report! I'll take a look into this when I get some cycles and report back. In the meantime, the larger issue with pytest 4 is here: https://github.com/wolever/parameterized/issues/34

I'll post an update when I've figured out how to get this working.

**Comment by jatinp1** [comment]
Calling fixture directly feature is deprecated in 4.0 version. Install 3.10.0 version. It will work

**Comment by asher-dev** [comment]
I don't think there's an easy fix for this, but it can be done with a call to `request.getfixturevalue(fixture_name)` on the fixture request object (which is a parameter for fixtures) as long as there's a fixture context to call it from. I don't have familiarity with `parameterized` implementation so I can't suggest where to use it.

**Comment by wolever** [comment]
Hey folks - after consultation with @asher-dev, I don't believe this is a feature parameterized should support.

As mentioned, this appears to be an abuse (or, at least, misuse) of pytest fixtures as implemented in pytest4… so it might be _possible_ to hack around, but I don't believe there's a strong usecase.

If you believe you have a usecase that is inline with "correct" pytest fixture usage, please comment here; I'm happy to reopen the issue if my understanding is faulty.
