### ISSUE TITLE
LICENSE.txt states exception but there appears to be none?

### ISSUE THREAD

**Issue by joachimmetz** [wolever/parameterized#62]
From: https://github.com/wolever/parameterized/blob/master/LICENSE.txt
`tl;dr: all code code is licensed under simplified BSD, unless stated otherwise.`

Quickly searching the code I see no exception to the license. Is my assessment correct?

If so, please consider removing this exception clause, seeing (for me at least) it add confusion

If there are exceptions, please state their path in the LICENSE.txt file

thanks in advance

**Comment by wolever** [comment]
Thanks!
