### ISSUE TITLE
"from parameterized import parameterized_class" fails

### ISSUE THREAD

**Issue by TobyLL** [wolever/parameterized#64]
After downloading and installing the latest version of parameterized on 2019-01-14, I tried to use the `@paramaterized_class` decorator in Python 2.7 as per the example given in the documentation.  However, the following error was thrown:
`ImportError: cannot import name parameterized_class`

I believe that adding parameterized_class to `parameterized/__init__.py` as follows fixes the issue:
`from .parameterized import parameterized, param, parameterized_class`

**Comment by wolever** [comment]
Thanks!
