### ISSUE TITLE
Add equivalent of name_func for parameterized_class

### ISSUE THREAD

**Issue by jeremylanglois** [wolever/parameterized#69]
Hello,

I would be convenient to add "name_func" argument to parameterized_class since the current behaviour is only adding suffix if parameters are of type string.

Thanks!

**Comment by wolever** [comment]
Hey! That sounds useful! I'd absolutely consider a PR if you wanted to submit one, otherwise I'll keep this issue open so I can let you know when I get around to it :)

**Comment by jeremylanglois** [comment]
Great, I will give it a shot!

**Comment by Skeen** [comment]
I was just looking for this! +1

**Comment by jaredkerim** [comment]
@wolever I would also like this.

**Comment by wolever** [comment]
Wow, didn't realize this would be so popular! I don't know exactly when I'll have cycles to add it, but hopefully in the next ~week or two, and would be happy to help someone with a PR if they want to take point!

**Comment by wolever** [comment]
A `classname_func` argument has been added, and it will even be documented shortly!

Thanks!
