### ISSUE TITLE
0.7.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [wolever/parameterized#84]
<pre>Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.Z6weJ6
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd parameterized-0.7.1
+ export PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-parameterized-0.7.1-2.fc32.x86_64/usr/lib/python3.8/site-packages
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-parameterized-0.7.1-2.fc32.x86_64/usr/lib/python3.8/site-packages
+ nosetests-3.8 -v
parameterized.test.TestOldStyleClass.test_old_style_classes_0_foo ... ok
parameterized.test.TestOldStyleClass.test_old_style_classes_1_bar ... ok
test_on_TestCase2_custom_name_42 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase2_custom_name_foo0 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase2_custom_name_foo1 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase2_custom_name_foo2 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_0 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_1_foo0 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_2_foo1 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_3_foo2 (parameterized.test.TestParamerizedOnTestCase) ... ok
parameterized.test.TestParameterized.test_instance_method(42, {}) ... ok
parameterized.test.TestParameterized.test_instance_method(&apos;foo0&apos;, {}) ... ok
parameterized.test.TestParameterized.test_instance_method(&apos;foo1&apos;, {}) ... ok
parameterized.test.TestParameterized.test_instance_method(&apos;foo2&apos;, {&apos;bar&apos;: 42}) ... ok
test_method (parameterized.test.TestParameterizedClassDict_0) ... ok
test_method (parameterized.test.TestParameterizedClassDict_1) ... ok
test_method_a (parameterized.test.TestParameterizedClass_0_foo) ... ok
test_method_b (parameterized.test.TestParameterizedClass_0_foo) ... ok
test_method_a (parameterized.test.TestParameterizedClass_1_bar) ... ok
test_method_b (parameterized.test.TestParameterizedClass_1_bar) ... ok
test_method_a (parameterized.test.TestParameterizedClass_2) ... ok
test_method_b (parameterized.test.TestParameterizedClass_2) ... ok
stuff ... FAIL
Documentation [with foo=&apos;foo&apos;, bar=12] ... FAIL
[with foo=&apos;foo&apos;] ... FAIL
Documentation [with foo=&apos;foo&apos;]. ... FAIL
Documentation [with foo=&apos;foo&apos;]. ... FAIL
Döcumentation [with foo=&apos;foo&apos;]. ... FAIL
Documentation [with foo=&apos;foo&apos;, bar=12] ... FAIL
test_multiple_function_patch_decorator_0 (parameterized.test.TestParameterizedExpandWithMockPatchForClass) ... ok
test_multiple_function_patch_decorator_1_foo0 (parameterized.test.TestParameterizedExpandWithMockPatchForClass) ... ok
test_multiple_function_patch_decorator_2_foo1 (parameterized.test.TestParameterizedExpandWithMockPatchForClass) ... ok
test_one_function_patch_decorator_0 (parameterized.test.TestParameterizedExpandWithMockPatchForClass) ... ok
test_one_function_patch_decorator_1_foo0 (parameterized.test.TestParameterizedExpandWithMockPatchForClass) ... ok
test_one_function_patch_decorator_2_foo1 (parameterized.test.TestParameterizedExpandWithMockPatchForClass) ... ok
parameterized.test.TestParameterizedExpandWithNoExpand.test_patch_class_no_expand(42, 51, {}) ... ok
test_multiple_function_patch_decorator_0 (parameterized.test.TestParameterizedExpandWithNoMockPatchForClass) ... ok
test_multiple_function_patch_decorator_1_foo0 (parameterized.test.TestParameterizedExpandWithNoMockPatchForClass) ... ok
test_multiple_function_patch_decorator_2_foo1 (parameterized.test.TestParameterizedExpandWithNoMockPatchForClass) ... ok
test_one_function_patch_decorator_0 (parameterized.test.TestParameterizedExpandWithNoMockPatchForClass) ... ok
test_one_function_patch_decorator_1_foo0 (parameterized.test.TestParameterizedExpandWithNoMockPatchForClass) ... ok
test_one_function_patch_decorator_2_foo1 (parameterized.test.TestParameterizedExpandWithNoMockPatchForClass) ... ok
parameterized.test.TestParameterizedExpandWithNoMockPatchForClassNoExpand.test_patch_no_expand(42, 51, {}) ... ok
parameterized.test.TestSetupTeardown.test_setup(1, {}) ... ok
parameterized.test.TestSetupTeardown.test_setup(2, {}) ... ok
parameterized.test.test_warns_when_using_parameterized_with_TestCase ... ok
parameterized.test.test_helpful_error_on_invalid_parameters ... ok
parameterized.test.test_helpful_error_on_empty_iterable_input ... ok
parameterized.test.test_skip_test_on_empty_iterable ... ok
parameterized.test.test_cases_over_10(0, 1, {}) ... ok
parameterized.test.test_cases_over_10(1, 2, {}) ... ok
parameterized.test.test_cases_over_10(2, 3, {}) ... ok
parameterized.test.test_cases_over_10(3, 4, {}) ... ok
parameterized.test.test_cases_over_10(4, 5, {}) ... ok
parameterized.test.test_cases_over_10(5, 6, {}) ... ok
parameterized.test.test_cases_over_10(6, 7, {}) ... ok
parameterized.test.test_cases_over_10(7, 8, {}) ... ok
parameterized.test.test_cases_over_10(8, 9, {}) ... ok
parameterized.test.test_cases_over_10(9, 10, {}) ... ok
parameterized.test.test_cases_over_10(10, 11, {}) ... ok
parameterized.test.test_helpful_error_on_empty_iterable_input_expand ... ok
parameterized.test.test_mock_patch_standalone_function(42, {}) ... ok
parameterized.test.test_naked_function(42, {}) ... ok
parameterized.test.test_naked_function(&apos;foo0&apos;, {}) ... ok
parameterized.test.test_naked_function(&apos;foo1&apos;, {}) ... ok
parameterized.test.test_naked_function(&apos;foo2&apos;, {&apos;bar&apos;: 42}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;&apos;, param(*(), **{}), [], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;*a, **kw&apos;, param(*(), **{}), [], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;*a, **kw&apos;, param(*(1,), **{&apos;foo&apos;: 42}), [(&apos;*a&apos;, (1,)), (&apos;**kw&apos;, {&apos;foo&apos;: 42})], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;foo&apos;, param(*(1,), **{}), [(&apos;foo&apos;, 1)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;foo, *a&apos;, param(*(1,), **{}), [(&apos;foo&apos;, 1)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;foo, *a&apos;, param(*(1, 9), **{}), [(&apos;foo&apos;, 1), (&apos;*a&apos;, (9,))], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;foo, *a, **kw&apos;, param(*(1,), **{&apos;bar&apos;: 9}), [(&apos;foo&apos;, 1), (&apos;**kw&apos;, {&apos;bar&apos;: 9})], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x=9&apos;, param(*(), **{}), [(&apos;x&apos;, 9)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x=9&apos;, param(*(1,), **{}), [(&apos;x&apos;, 1)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x, y=9, *a, **kw&apos;, param(*(1,), **{}), [(&apos;x&apos;, 1), (&apos;y&apos;, 9)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x, y=9, *a, **kw&apos;, param(*(1, 2), **{}), [(&apos;x&apos;, 1), (&apos;y&apos;, 2)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x, y=9, *a, **kw&apos;, param(*(1, 2, 3), **{}), [(&apos;x&apos;, 1), (&apos;y&apos;, 2), (&apos;*a&apos;, (3,))], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x, y=9, *a, **kw&apos;, param(*(1,), **{&apos;y&apos;: 2}), [(&apos;x&apos;, 1), (&apos;y&apos;, 2)], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x, y=9, *a, **kw&apos;, param(*(1,), **{&apos;z&apos;: 2}), [(&apos;x&apos;, 1), (&apos;y&apos;, 9), (&apos;**kw&apos;, {&apos;z&apos;: 2})], {}) ... ok
parameterized.test.test_parameterized_argument_value_pairs(&apos;x, y=9, *a, **kw&apos;, param(*(1, 2, 3), **{&apos;z&apos;: 3}), [(&apos;x&apos;, 1), (&apos;y&apos;, 2), (&apos;*a&apos;, (3,)), (&apos;**kw&apos;, {&apos;z&apos;: 3})], {}) ... ok
parameterized.test.test_short_repr(&apos;abcd&apos;, &quot;&apos;abcd&apos;&quot;, {}) ... ok
parameterized.test.test_short_repr(&apos;123456789&apos;, &quot;&apos;12...89&apos;&quot;, {}) ... ok
parameterized.test.test_short_repr(123456789, &apos;123...789&apos;, {}) ... ok
parameterized.test.test_short_repr(123456789, &apos;12...89&apos;, 4, {}) ... ok
Docstring! [with input=&apos;foo&apos;] ... ok
parameterized.test.test_wrapped_iterable_input(&apos;foo&apos;, {}) ... ok
parameterized.test.test_helpful_error_on_non_iterable_input ... ok
parameterized.test.test_old_style_classes ... SKIP: Py3 doesn&apos;t have old-style classes

======================================================================
FAIL: stuff
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 265, in test_custom_doc_func
    self._assert_docstring(&quot;stuff&quot;)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

======================================================================
FAIL: Documentation [with foo=&apos;foo&apos;, bar=12]
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 295, in test_default_values_get_correct_value
    self._assert_docstring(&quot;Documentation [with foo=%r, bar=%r]&quot; %(foo, bar))
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

======================================================================
FAIL: [with foo=&apos;foo&apos;]
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 275, in test_empty_docstring
    self._assert_docstring(&quot;[with foo=%r]&quot; %(foo, ))
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

======================================================================
FAIL: Documentation [with foo=&apos;foo&apos;].
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 282, in test_multiline_documentation
    self._assert_docstring(
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

======================================================================
FAIL: Documentation [with foo=&apos;foo&apos;].
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 270, in test_single_line_docstring
    self._assert_docstring(&quot;Documentation [with foo=%r].&quot; %(foo, ))
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

======================================================================
FAIL: Döcumentation [with foo=&apos;foo&apos;].
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 290, in test_unicode_docstring
    self._assert_docstring(u&quot;Döcumentation [with foo=%r].&quot; %(foo, ))
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

======================================================================
FAIL: Documentation [with foo=&apos;foo&apos;, bar=12]
----------------------------------------------------------------------
Traceback (most recent call last):
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/parameterized.py&quot;, line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 302, in test_with_leading_newline
    self._assert_docstring(&quot;Documentation [with foo=%r, bar=%r]&quot; %(foo, bar), rstrip=True)
  File &quot;/home/tkloczko/rpmbuild/BUILD/parameterized-0.7.1/parameterized/test.py&quot;, line 255, in _assert_docstring
    raise AssertionError(&quot;uh oh, unittest changed a local variable name&quot;)
AssertionError: uh oh, unittest changed a local variable name

----------------------------------------------------------------------
Ran 89 tests in 0.141s

FAILED (SKIP=1, failures=7)
error: Bad exit status from /var/tmp/rpm-tmp.Z6weJ6 (%check)
</pre>

**Comment by jikamens** [comment]
Anybody here? Would be nice for parameterized to be compatible with Python 3.8!

**Comment by vpayno** [comment]
@jikamens https://github.com/wolever/parameterized/pull/75/files - this fixed it for me.

**Comment by kloczek** [comment]
> @jikamens https://github.com/wolever/parameterized/pull/75/files - this fixed it for me.

But that patch is already part of the 0.7.1.

**Comment by wolever** [comment]
Should be fixed now!

**Comment by kloczek** [comment]
> Should be fixed now!

Yep 0.7.3 looks good now.

Thx :)
