### ISSUE TITLE
parameterized_class custom suffix ?

### ISSUE THREAD

**Issue by stuaxo** [wolever/parameterized#96]
Hi,
   How can I set a custom suffix for parameterized_class ?

I tried looking at the code + docs to grok this, but don't get it.

I've roughly got something like this:

```python
addons = ["linkifier", "release_check"]
@parameterized_class([{"addon_name": addon_name for addon_name in addons}])
class AddonTester(TestCase):
    addon_name

    # tests...
```

I'd like the addon_name to make addon_name the class name suffix, but I always just end up with numbers.

Reading the other tickets it looks like it might be possible if I use string parameters, but I'm not sure how to do this.

**Comment by matthijskooijman** [comment]
See #87 for an example without dictionaries (with dictionaries, this does not seem to be possible). I think this issue could be closed in favor of that one.

**Comment by stuaxo** [comment]
Cheers, will close.

I've been experimenting with a patch that works with dictionaries (ironically only dicts currently).

**Comment by stuaxo** [comment]
It looks like https://github.com/wolever/parameterized/pull/74 had what I need, a callback to change the class name.

I wonder if it will land though ?
